<?php

$defaults = [
    'enabled' => true,
    'requires_confirmation' => false,
    'requires_password_confirmation' => false,
    'supports_streaming' => true,
    'timeout_seconds' => (int) env('ACTION_DEFAULT_TIMEOUT_SECONDS', 120),
    'allowed_options' => [],
    'preflight' => [],
    'concurrent' => false,
    'backup_required' => false,
];

return [
    'mock' => env('YOUPANEL_ACTION_DRIVER', env('APP_ENV') === 'production' ? 'process' : 'mock') === 'mock',
    'actions' => [
        'laravel.about' => $defaults + ['name' => 'Laravel about', 'description' => 'Show Laravel application information.', 'category' => 'laravel', 'risk_level' => 'low', 'required_role' => 'developer', 'component_types' => ['laravel'], 'executor' => 'laravel', 'command' => ['php', 'artisan', 'about']],
        'laravel.clear_cache' => $defaults + ['name' => 'Clear Laravel cache', 'description' => 'Clear framework caches without restarting the application.', 'category' => 'laravel', 'risk_level' => 'low', 'required_role' => 'editor', 'component_types' => ['laravel'], 'executor' => 'laravel', 'command' => ['php', 'artisan', 'optimize:clear']],
        'laravel.cache_config' => $defaults + ['name' => 'Cache config', 'description' => 'Build Laravel config cache.', 'category' => 'laravel', 'risk_level' => 'medium', 'required_role' => 'developer', 'component_types' => ['laravel'], 'executor' => 'laravel', 'command' => ['php', 'artisan', 'config:cache'], 'requires_confirmation' => true],
        'laravel.cache_routes' => $defaults + ['name' => 'Cache routes', 'description' => 'Build Laravel route cache.', 'category' => 'laravel', 'risk_level' => 'medium', 'required_role' => 'developer', 'component_types' => ['laravel'], 'executor' => 'laravel', 'command' => ['php', 'artisan', 'route:cache'], 'requires_confirmation' => true],
        'laravel.cache_views' => $defaults + ['name' => 'Cache views', 'description' => 'Compile Blade views.', 'category' => 'laravel', 'risk_level' => 'low', 'required_role' => 'editor', 'component_types' => ['laravel'], 'executor' => 'laravel', 'command' => ['php', 'artisan', 'view:cache']],
        'laravel.optimize' => $defaults + ['name' => 'Optimize Laravel', 'description' => 'Run Laravel optimize.', 'category' => 'laravel', 'risk_level' => 'medium', 'required_role' => 'developer', 'component_types' => ['laravel'], 'executor' => 'laravel', 'command' => ['php', 'artisan', 'optimize'], 'requires_confirmation' => true],
        'laravel.migrate_status' => $defaults + ['name' => 'Migration status', 'description' => 'Inspect migration status without changing the database.', 'category' => 'laravel', 'risk_level' => 'low', 'required_role' => 'developer', 'component_types' => ['laravel'], 'executor' => 'laravel', 'command' => ['php', 'artisan', 'migrate:status']],
        'laravel.migrate' => $defaults + ['name' => 'Run migrations', 'description' => 'Run pending Laravel migrations with force after confirmation.', 'category' => 'laravel', 'risk_level' => 'high', 'required_role' => 'developer', 'component_types' => ['laravel'], 'executor' => 'laravel', 'command' => ['php', 'artisan', 'migrate', '--force'], 'requires_confirmation' => true, 'requires_password_confirmation' => true, 'backup_required' => true, 'timeout_seconds' => 300],
        'laravel.maintenance_enable' => $defaults + ['name' => 'Enable maintenance', 'description' => 'Put Laravel into maintenance mode.', 'category' => 'laravel', 'risk_level' => 'high', 'required_role' => 'developer', 'component_types' => ['laravel'], 'executor' => 'laravel', 'command' => ['php', 'artisan', 'down', '--render=errors::503'], 'requires_confirmation' => true, 'requires_password_confirmation' => true],
        'laravel.maintenance_disable' => $defaults + ['name' => 'Disable maintenance', 'description' => 'Take Laravel out of maintenance mode.', 'category' => 'laravel', 'risk_level' => 'medium', 'required_role' => 'developer', 'component_types' => ['laravel'], 'executor' => 'laravel', 'command' => ['php', 'artisan', 'up'], 'requires_confirmation' => true],
        'laravel.queue_restart' => $defaults + ['name' => 'Restart queues', 'description' => 'Signal Laravel queue workers to restart gracefully.', 'category' => 'laravel', 'risk_level' => 'medium', 'required_role' => 'developer', 'component_types' => ['laravel'], 'executor' => 'laravel', 'command' => ['php', 'artisan', 'queue:restart'], 'requires_confirmation' => true],
        'laravel.scheduler_list' => $defaults + ['name' => 'List scheduler', 'description' => 'Show configured Laravel scheduled tasks.', 'category' => 'laravel', 'risk_level' => 'low', 'required_role' => 'developer', 'component_types' => ['laravel'], 'executor' => 'laravel', 'command' => ['php', 'artisan', 'schedule:list']],
        'laravel.test' => $defaults + ['name' => 'Run Laravel tests', 'description' => 'Run the project test suite.', 'category' => 'laravel', 'risk_level' => 'medium', 'required_role' => 'developer', 'component_types' => ['laravel'], 'executor' => 'laravel', 'command' => ['php', 'artisan', 'test', '--compact'], 'requires_confirmation' => true, 'timeout_seconds' => 300],

        'composer.validate' => $defaults + ['name' => 'Validate Composer', 'description' => 'Validate composer.json.', 'category' => 'composer', 'risk_level' => 'low', 'required_role' => 'developer', 'component_types' => ['laravel', 'custom'], 'executor' => 'composer', 'command' => ['composer', 'validate', '--no-interaction']],
        'composer.install_production' => $defaults + ['name' => 'Composer production install', 'description' => 'Install locked production dependencies.', 'category' => 'composer', 'risk_level' => 'medium', 'required_role' => 'developer', 'component_types' => ['laravel', 'custom'], 'executor' => 'composer', 'command' => ['composer', 'install', '--no-dev', '--optimize-autoloader', '--no-interaction'], 'requires_confirmation' => true, 'timeout_seconds' => 600],
        'composer.dump_autoload' => $defaults + ['name' => 'Dump autoload', 'description' => 'Regenerate optimized Composer autoload files.', 'category' => 'composer', 'risk_level' => 'low', 'required_role' => 'developer', 'component_types' => ['laravel', 'custom'], 'executor' => 'composer', 'command' => ['composer', 'dump-autoload', '--optimize']],
        'composer.audit' => $defaults + ['name' => 'Composer audit', 'description' => 'Audit PHP dependencies.', 'category' => 'composer', 'risk_level' => 'low', 'required_role' => 'developer', 'component_types' => ['laravel', 'custom'], 'executor' => 'composer', 'command' => ['composer', 'audit']],

        'npm.install_ci' => $defaults + ['name' => 'npm ci', 'description' => 'Install locked Node dependencies.', 'category' => 'npm', 'risk_level' => 'medium', 'required_role' => 'developer', 'component_types' => ['nextjs', 'vite', 'node'], 'executor' => 'npm', 'command' => ['npm', 'ci'], 'requires_confirmation' => true, 'timeout_seconds' => 600],
        'npm.build' => $defaults + ['name' => 'npm build', 'description' => 'Run the configured build script.', 'category' => 'npm', 'risk_level' => 'medium', 'required_role' => 'developer', 'component_types' => ['nextjs', 'vite', 'node'], 'executor' => 'npm', 'command' => ['npm', 'run', 'build'], 'requires_confirmation' => true, 'timeout_seconds' => 600],
        'npm.test' => $defaults + ['name' => 'npm test', 'description' => 'Run the configured test script.', 'category' => 'npm', 'risk_level' => 'medium', 'required_role' => 'developer', 'component_types' => ['nextjs', 'vite', 'node'], 'executor' => 'npm', 'command' => ['npm', 'test'], 'requires_confirmation' => true, 'timeout_seconds' => 300],
        'npm.lint' => $defaults + ['name' => 'npm lint', 'description' => 'Run the configured lint script.', 'category' => 'npm', 'risk_level' => 'low', 'required_role' => 'developer', 'component_types' => ['nextjs', 'vite', 'node'], 'executor' => 'npm', 'command' => ['npm', 'run', 'lint']],
        'npm.audit' => $defaults + ['name' => 'npm audit', 'description' => 'Audit Node dependencies.', 'category' => 'npm', 'risk_level' => 'low', 'required_role' => 'developer', 'component_types' => ['nextjs', 'vite', 'node'], 'executor' => 'npm', 'command' => ['npm', 'audit', '--audit-level=moderate']],

        'git.status' => $defaults + ['name' => 'Git status', 'description' => 'Inspect current branch, commit and changed files.', 'category' => 'git', 'risk_level' => 'low', 'required_role' => 'developer', 'component_types' => ['laravel', 'nextjs', 'vite', 'node', 'static', 'custom'], 'executor' => 'git', 'command' => ['git', 'status', '--short', '--branch']],
        'git.fetch' => $defaults + ['name' => 'Git fetch', 'description' => 'Fetch remote refs without changing files.', 'category' => 'git', 'risk_level' => 'low', 'required_role' => 'developer', 'component_types' => ['laravel', 'nextjs', 'vite', 'node', 'static', 'custom'], 'executor' => 'git', 'command' => ['git', 'fetch', '--prune']],
        'git.pull_fast_forward' => $defaults + ['name' => 'Git pull fast-forward', 'description' => 'Pull with --ff-only and refuse local changes.', 'category' => 'git', 'risk_level' => 'medium', 'required_role' => 'developer', 'component_types' => ['laravel', 'nextjs', 'vite', 'node', 'static', 'custom'], 'executor' => 'git', 'command' => ['git', 'pull', '--ff-only'], 'requires_confirmation' => true],
        'git.show_latest' => $defaults + ['name' => 'Latest commit', 'description' => 'Show the latest local commit.', 'category' => 'git', 'risk_level' => 'low', 'required_role' => 'developer', 'component_types' => ['laravel', 'nextjs', 'vite', 'node', 'static', 'custom'], 'executor' => 'git', 'command' => ['git', 'log', '-1', '--pretty=%h %s']],
        'git.list_branches' => $defaults + ['name' => 'List branches', 'description' => 'List local branches.', 'category' => 'git', 'risk_level' => 'low', 'required_role' => 'developer', 'component_types' => ['laravel', 'nextjs', 'vite', 'node', 'static', 'custom'], 'executor' => 'git', 'command' => ['git', 'branch', '--list']],

        'pm2.status' => $defaults + ['name' => 'PM2 status', 'description' => 'Inspect the configured PM2 process.', 'category' => 'pm2', 'risk_level' => 'low', 'required_role' => 'developer', 'component_types' => ['nextjs', 'node', 'worker'], 'executor' => 'pm2', 'command' => ['pm2', 'describe', '__PROCESS_NAME__']],
        'pm2.restart_assigned_process' => $defaults + ['name' => 'Restart assigned PM2 process', 'description' => 'Restart only the configured PM2 process.', 'category' => 'pm2', 'risk_level' => 'medium', 'required_role' => 'developer', 'component_types' => ['nextjs', 'node', 'worker'], 'executor' => 'pm2', 'command' => ['pm2', 'restart', '__PROCESS_NAME__'], 'requires_confirmation' => true],
        'pm2.reload_assigned_process' => $defaults + ['name' => 'Reload assigned PM2 process', 'description' => 'Reload only the configured PM2 process.', 'category' => 'pm2', 'risk_level' => 'medium', 'required_role' => 'developer', 'component_types' => ['nextjs', 'node', 'worker'], 'executor' => 'pm2', 'command' => ['pm2', 'reload', '__PROCESS_NAME__'], 'requires_confirmation' => true],
        'pm2.logs_snapshot' => $defaults + ['name' => 'PM2 logs snapshot', 'description' => 'Capture recent logs for the configured PM2 process.', 'category' => 'pm2', 'risk_level' => 'low', 'required_role' => 'developer', 'component_types' => ['nextjs', 'node', 'worker'], 'executor' => 'pm2', 'command' => ['pm2', 'logs', '__PROCESS_NAME__', '--lines', '100', '--nostream']],

        'website.health_check' => $defaults + ['name' => 'Health check', 'description' => 'Run the configured website health check.', 'category' => 'website', 'risk_level' => 'low', 'required_role' => 'viewer', 'component_types' => ['laravel', 'nextjs', 'vite', 'node', 'static', 'custom'], 'executor' => 'website', 'command' => null],
        'website.create_backup' => $defaults + ['name' => 'Create backup', 'description' => 'Create a recoverable backup into private storage.', 'category' => 'backup', 'risk_level' => 'medium', 'required_role' => 'developer', 'component_types' => ['laravel', 'nextjs', 'vite', 'node', 'static', 'custom'], 'executor' => 'backup', 'command' => null, 'requires_confirmation' => true, 'timeout_seconds' => 600],
        'website.restore_backup' => $defaults + ['name' => 'Restore backup', 'description' => 'Stage a backup restore for validation.', 'category' => 'backup', 'risk_level' => 'high', 'required_role' => 'owner', 'component_types' => ['laravel', 'nextjs', 'vite', 'node', 'static', 'custom'], 'executor' => 'backup', 'command' => null, 'requires_confirmation' => true, 'requires_password_confirmation' => true, 'enabled' => true],
        'website.collect_diagnostics' => $defaults + ['name' => 'Collect diagnostics', 'description' => 'Collect safe website diagnostics.', 'category' => 'website', 'risk_level' => 'low', 'required_role' => 'developer', 'component_types' => ['laravel', 'nextjs', 'vite', 'node', 'static', 'custom'], 'executor' => 'website', 'command' => null],

        'service.nginx_test' => $defaults + ['name' => 'Nginx configuration test', 'description' => 'Future privileged-agent action. Disabled until production runner exists.', 'category' => 'service', 'risk_level' => 'high', 'required_role' => 'owner', 'component_types' => [], 'executor' => 'disabled', 'command' => null, 'enabled' => false],
        'service.nginx_reload' => $defaults + ['name' => 'Nginx reload', 'description' => 'Future privileged-agent action. Disabled until production runner exists.', 'category' => 'service', 'risk_level' => 'high', 'required_role' => 'owner', 'component_types' => [], 'executor' => 'disabled', 'command' => null, 'enabled' => false],
        'service.php_fpm_reload' => $defaults + ['name' => 'PHP-FPM reload', 'description' => 'Future privileged-agent action. Disabled until production runner exists.', 'category' => 'service', 'risk_level' => 'high', 'required_role' => 'owner', 'component_types' => [], 'executor' => 'disabled', 'command' => null, 'enabled' => false],
        'service.cloudflared_restart' => $defaults + ['name' => 'Cloudflared restart', 'description' => 'Future privileged-agent action. Disabled until production runner exists.', 'category' => 'service', 'risk_level' => 'high', 'required_role' => 'owner', 'component_types' => [], 'executor' => 'disabled', 'command' => null, 'enabled' => false],
    ],
];
